import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Dict

from .config import GMAIL_USER, GMAIL_APP_PASSWORD


def send_daily_email(jobs: List[Dict], to_email: str):
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        print("[Email] Skipped — Gmail credentials not configured")
        return

    tiers = {"A": [], "B": [], "C": [], "D": []}
    for job in jobs:
        tiers.setdefault(job.get("tier", "D"), []).append(job)

    total_a = len(tiers["A"])
    total_b = len(tiers["B"])
    date_str = datetime.now().strftime("%B %d, %Y")

    html = f"""
<html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
<h2 style="color: #1a1a2e;">🎯 Daily Job Matches — {date_str}</h2>
<p><b>{len(jobs)} total jobs</b> | {total_a} Tier A | {total_b} Tier B</p>
<hr>

{_tier_section(tiers["A"], "A", "🔥", "#d4edda", "85+ ATS Match")}
{_tier_section(tiers["B"], "B", "⭐", "#cce5ff", "75-84 ATS Match")}
{_tier_section(tiers["C"], "C", "✅", "#fff3cd", "65-74 ATS Match")}

<hr>
<p style="color: #999; font-size: 12px;">
  Generated by Job Automation Tool •
  <a href="http://localhost:5173">View Dashboard</a>
</p>
</body></html>
"""

    msg = MIMEMultipart("alternative")
    msg["From"] = GMAIL_USER
    msg["To"] = to_email
    msg["Subject"] = f"📬 {total_a} High-Match Jobs Today ({date_str})"
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.send_message(msg)
        print(f"[Email] Sent to {to_email}")
    except Exception as e:
        print(f"[Email] Failed: {e}")


def _tier_section(jobs: List[Dict], tier: str, icon: str, color: str, label: str) -> str:
    if not jobs:
        return ""

    rows = ""
    for j in jobs[:15]:  # Cap at 15 per tier in email
        score = j.get("best_score", 0)
        resume = j.get("best_resume", "")
        jtype = "W2/Contract" if j.get("job_type") == "contract" else "Full-Time"
        rows += f"""
<tr>
  <td style="padding: 8px; border-bottom: 1px solid #eee;">
    <b>{j['company']}</b><br>
    <span style="color: #555;">{j['role']}</span><br>
    <small>📍 {j['location']} | {jtype} | 📄 {resume} Resume | 🌐 {j['source']}</small>
  </td>
  <td style="padding: 8px; text-align: center; border-bottom: 1px solid #eee;">
    <span style="font-size: 20px; font-weight: bold; color: #333;">{score:.0f}%</span>
  </td>
  <td style="padding: 8px; text-align: center; border-bottom: 1px solid #eee;">
    <a href="{j['apply_url']}" style="background:#0066cc; color:white; padding:6px 14px;
       border-radius:4px; text-decoration:none; font-size:13px;">Apply</a>
  </td>
</tr>"""

    return f"""
<h3 style="background:{color}; padding: 10px; border-radius:6px;">
  {icon} Tier {tier} — {label} ({len(jobs)} jobs)
</h3>
<table style="width:100%; border-collapse:collapse;">
  <tr style="background:#f8f9fa;">
    <th style="padding:8px; text-align:left;">Company / Role</th>
    <th style="padding:8px;">Score</th>
    <th style="padding:8px;">Action</th>
  </tr>
  {rows}
</table>
{"<p><i>... and " + str(len(jobs) - 15) + " more in this tier</i></p>" if len(jobs) > 15 else ""}
"""
